
spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:mem:test
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
mail:
    address:
        admin: admin@gmail.com

jwt:
    key: seulime12341234123412341234123412341234
    access-token-expiration-minutes: 30
    refresh-token-expiration-minutes: 420
    
=======

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sys?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Baek102504!

spring.jpa.properties.hibernate.show_sql=true

spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.type.descriptor.sql=trace

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

