spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://database-1.cws5cfcezt45.ap-northeast-2.rds.amazonaws.com:3306/sys?serverTimezone=UTC
        username: admin
        password: Baek102504!
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
           format_sql: true
           show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace
mail:
    address:
        admin: admin@gmail.com

jwt:
    key: seulime12341234123412341234123412341234
    access-token-expiration-minutes: 30
    refresh-token-expiration-minutes: 420










